package com.chengjf.shiro.demo.shiro.mapper;

import com.chengjf.shiro.demo.shiro.entity.SysMenuEntity;
import com.chengjf.shiro.demo.shiro.entity.SysMenuEntityExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SysMenuEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu
     *
     * @mbg.generated
     */
    long countByExample(SysMenuEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu
     *
     * @mbg.generated
     */
    int deleteByExample(SysMenuEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu
     *
     * @mbg.generated
     */
    int insert(SysMenuEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu
     *
     * @mbg.generated
     */
    int insertSelective(SysMenuEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu
     *
     * @mbg.generated
     */
    List<SysMenuEntity> selectByExample(SysMenuEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu
     *
     * @mbg.generated
     */
    SysMenuEntity selectByPrimaryKey(Long menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SysMenuEntity record, @Param("example") SysMenuEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SysMenuEntity record, @Param("example") SysMenuEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysMenuEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_menu
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysMenuEntity record);

    List<SysMenuEntity> queryUserList(Long userId);
}