package com.chengjf.shiro.demo.shiro.mapper;

import com.chengjf.shiro.demo.shiro.entity.SysUserRoleEntity;
import com.chengjf.shiro.demo.shiro.entity.SysUserRoleEntityExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SysUserRoleEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user_role
     *
     * @mbg.generated
     */
    long countByExample(SysUserRoleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user_role
     *
     * @mbg.generated
     */
    int deleteByExample(SysUserRoleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user_role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user_role
     *
     * @mbg.generated
     */
    int insert(SysUserRoleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user_role
     *
     * @mbg.generated
     */
    int insertSelective(SysUserRoleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user_role
     *
     * @mbg.generated
     */
    List<SysUserRoleEntity> selectByExample(SysUserRoleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user_role
     *
     * @mbg.generated
     */
    SysUserRoleEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SysUserRoleEntity record, @Param("example") SysUserRoleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SysUserRoleEntity record, @Param("example") SysUserRoleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SysUserRoleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SysUserRoleEntity record);
}